name: Deploy Multi-Environment

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.repository }}-deploy-dev
      cancel-in-progress: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t apis-auth-api-dev:latest -f ./infra/APIs/auth-api-dev/Dockerfile .

      - name: Tag image for private registry
        run: |
          docker tag apis-auth-api-dev:latest ${{ secrets.VPS_IP }}:5000/apis-auth-api:latest

      - name: Push to private registry (insecure)
        run: |
          docker push ${{ secrets.VPS_IP }}:5000/apis-auth-api:latest

      - name: SSH Deploy DEV
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_DEV_HOST }}
          username: ${{ secrets.VPS_DEV_USER }}
          key: ${{ secrets.VPS_DEV_SSH_KEY }}
          script: |
            set -e

            echo "🚀 Atualizando código"
            cd ~/deploy/dev/infra
            git fetch origin && git checkout develop && git pull

            echo "📦 Parando container antigo"
            cd ./APIs
            docker compose stop auth-api-dev || true
            docker compose rm -f auth-api-dev || true

            echo "📥 Puxando nova imagem do registry"
            docker rmi ${{ secrets.VPS_IP }}:5000/apis-auth-api:latest || true
            docker pull ${{ secrets.VPS_IP }}:5000/apis-auth-api:latest

            echo "🚀 Subindo container com nova imagem"
            docker compose up -d auth-api-dev
          debug: true
