name: Deploy Multi-Environment

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.repository }}-deploy-dev
      cancel-in-progress: false
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/auth-api-dev:latest
      GITHUB_USER: ${{ secrets.GITHUB_USER }}
      GIT_PAT: ${{ secrets.GIT_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GIT_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: SSH Deploy DEV
        uses: appleboy/ssh-action@v0.1.10
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_USER: ${{ env.GITHUB_USER }}
          GIT_PAT: ${{ env.GIT_PAT }}
        with:
          host: ${{ secrets.VPS_DEV_HOST }}
          username: ${{ secrets.VPS_DEV_USER }}
          key: ${{ secrets.VPS_DEV_SSH_KEY }}
          script: |
            set -e

            echo "🚀 Atualizando código"
            cd ~/deploy/dev/infra
            git remote set-url origin https://github.com/MinhaVan/infra.git
            git fetch origin
            git checkout develop
            git reset --hard origin/develop

            echo "📦 Parando container antigo"
            cd ./APIs
            docker compose stop auth-api-dev || true
            docker compose rm -f auth-api-dev || true

            echo "📥 Removendo imagem antiga localmente"
            if docker images -q $IMAGE_NAME > /dev/null 2>&1; then
              docker rmi $IMAGE_NAME || true
            else
              echo "Imagem $IMAGE_NAME não encontrada localmente, pulando remoção"
            fi

            echo "$GIT_PAT" | docker login ghcr.io -u $GITHUB_USER --password-stdin

            echo "📥 Puxando nova imagem do registry"
            docker pull $IMAGE_NAME

            echo "🚀 Subindo container com nova imagem"
            docker compose up -d auth-api-dev

            echo "📦 Containers ativos:"
            docker ps
          debug: true
